version: "3.9"

networks:
  acedia-net:

services:
  #######################################
  # Mongo
  #######################################
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    networks:
      - acedia-net
    ports:
      - "27017:27017"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    logging:
      driver: "none"

  mongo-client:
    container_name: mongo-client
    image: mongo:5.0
    networks:
      - acedia-net
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo-setup.sh" ]

  #######################################
  # Auth: API
  #######################################
  auth:
    container_name: auth
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - acedia-net
    command: yarn serve
    volumes:
      - .:/auth
    env_file:
      - .env.staging
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      
      